// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateChannelType int32

const (
	TemplateChannelType_CHANNELTYPE_UNSPECIFIED TemplateChannelType = 0
	TemplateChannelType_CHANNELTYPE_IN_APP      TemplateChannelType = 1
	TemplateChannelType_CHANNELTYPE_MESSENGER   TemplateChannelType = 2
	TemplateChannelType_CHANNELTYPE_EMAIL       TemplateChannelType = 3
	TemplateChannelType_CHANNELTYPE_SMS         TemplateChannelType = 4
)

// Enum value maps for TemplateChannelType.
var (
	TemplateChannelType_name = map[int32]string{
		0: "CHANNELTYPE_UNSPECIFIED",
		1: "CHANNELTYPE_IN_APP",
		2: "CHANNELTYPE_MESSENGER",
		3: "CHANNELTYPE_EMAIL",
		4: "CHANNELTYPE_SMS",
	}
	TemplateChannelType_value = map[string]int32{
		"CHANNELTYPE_UNSPECIFIED": 0,
		"CHANNELTYPE_IN_APP":      1,
		"CHANNELTYPE_MESSENGER":   2,
		"CHANNELTYPE_EMAIL":       3,
		"CHANNELTYPE_SMS":         4,
	}
)

func (x TemplateChannelType) Enum() *TemplateChannelType {
	p := new(TemplateChannelType)
	*p = x
	return p
}

func (x TemplateChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_service_proto_enumTypes[0].Descriptor()
}

func (TemplateChannelType) Type() protoreflect.EnumType {
	return &file_api_v1_service_proto_enumTypes[0]
}

func (x TemplateChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateChannelType.Descriptor instead.
func (TemplateChannelType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{0}
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Channel       TemplateChannelType    `protobuf:"varint,5,opt,name=channel,proto3,enum=ns.template.v1.TemplateChannelType" json:"channel,omitempty"`
	Variables     []string               `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_api_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Template) GetChannel() TemplateChannelType {
	if x != nil {
		return x.Channel
	}
	return TemplateChannelType_CHANNELTYPE_UNSPECIFIED
}

func (x *Template) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type TemplateGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Templates     []*Template            `protobuf:"bytes,4,rep,name=templates,proto3" json:"templates,omitempty"`
	MetaVariables map[string]string      `protobuf:"bytes,5,rep,name=meta_variables,json=metaVariables,proto3" json:"meta_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateGroup) Reset() {
	*x = TemplateGroup{}
	mi := &file_api_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateGroup) ProtoMessage() {}

func (x *TemplateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateGroup.ProtoReflect.Descriptor instead.
func (*TemplateGroup) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateGroup) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TemplateGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateGroup) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *TemplateGroup) GetMetaVariables() map[string]string {
	if x != nil {
		return x.MetaVariables
	}
	return nil
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Channel       TemplateChannelType    `protobuf:"varint,4,opt,name=channel,proto3,enum=ns.template.v1.TemplateChannelType" json:"channel,omitempty"`
	Variables     []string               `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_api_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateTemplateRequest) GetChannel() TemplateChannelType {
	if x != nil {
		return x.Channel
	}
	return TemplateChannelType_CHANNELTYPE_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type CreateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_api_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type CreateTemplatesRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Templates     []*CreateTemplateGroupRequest `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplatesRequest) Reset() {
	*x = CreateTemplatesRequest{}
	mi := &file_api_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplatesRequest) ProtoMessage() {}

func (x *CreateTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplatesRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTemplatesRequest) GetTemplates() []*CreateTemplateGroupRequest {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplatesResponse) Reset() {
	*x = CreateTemplatesResponse{}
	mi := &file_api_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplatesResponse) ProtoMessage() {}

func (x *CreateTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplatesResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_api_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTemplateRequest) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateResponse) Reset() {
	*x = UpdateTemplateResponse{}
	mi := &file_api_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateResponse) ProtoMessage() {}

func (x *UpdateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_api_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTemplateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_api_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{9}
}

type DeleteTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []string               `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplatesRequest) Reset() {
	*x = DeleteTemplatesRequest{}
	mi := &file_api_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplatesRequest) ProtoMessage() {}

func (x *DeleteTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplatesRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTemplatesRequest) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type DeleteTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplatesResponse) Reset() {
	*x = DeleteTemplatesResponse{}
	mi := &file_api_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplatesResponse) ProtoMessage() {}

func (x *DeleteTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplatesResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{11}
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_api_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetTemplateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_api_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          string                 `protobuf:"bytes,1,opt,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_api_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListTemplatesRequest) GetUids() string {
	if x != nil {
		return x.Uids
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_api_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateTemplateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Templates     []*Template            `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty"`
	MetaParams    map[string]string      `protobuf:"bytes,4,rep,name=meta_params,json=metaParams,proto3" json:"meta_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateGroupRequest) Reset() {
	*x = CreateTemplateGroupRequest{}
	mi := &file_api_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateGroupRequest) ProtoMessage() {}

func (x *CreateTemplateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTemplateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateGroupRequest) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *CreateTemplateGroupRequest) GetMetaParams() map[string]string {
	if x != nil {
		return x.MetaParams
	}
	return nil
}

type CreateTemplateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateGroupResponse) Reset() {
	*x = CreateTemplateGroupResponse{}
	mi := &file_api_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateGroupResponse) ProtoMessage() {}

func (x *CreateTemplateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{17}
}

type UpdateTemplateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateGroupRequest) Reset() {
	*x = UpdateTemplateGroupRequest{}
	mi := &file_api_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateGroupRequest) ProtoMessage() {}

func (x *UpdateTemplateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{18}
}

type UpdateTemplateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateGroupResponse) Reset() {
	*x = UpdateTemplateGroupResponse{}
	mi := &file_api_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateGroupResponse) ProtoMessage() {}

func (x *UpdateTemplateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{19}
}

type DeleteTemplateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateGroupRequest) Reset() {
	*x = DeleteTemplateGroupRequest{}
	mi := &file_api_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateGroupRequest) ProtoMessage() {}

func (x *DeleteTemplateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{20}
}

type DeleteTemplateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateGroupResponse) Reset() {
	*x = DeleteTemplateGroupResponse{}
	mi := &file_api_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateGroupResponse) ProtoMessage() {}

func (x *DeleteTemplateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{21}
}

type DeleteTemplateGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateGroupsRequest) Reset() {
	*x = DeleteTemplateGroupsRequest{}
	mi := &file_api_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateGroupsRequest) ProtoMessage() {}

func (x *DeleteTemplateGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateGroupsRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{22}
}

type DeleteTemplateGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateGroupsResponse) Reset() {
	*x = DeleteTemplateGroupsResponse{}
	mi := &file_api_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateGroupsResponse) ProtoMessage() {}

func (x *DeleteTemplateGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateGroupsResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{23}
}

type GetTemplateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateGroupRequest) Reset() {
	*x = GetTemplateGroupRequest{}
	mi := &file_api_v1_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateGroupRequest) ProtoMessage() {}

func (x *GetTemplateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateGroupRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{24}
}

type GetTemplateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateGroupResponse) Reset() {
	*x = GetTemplateGroupResponse{}
	mi := &file_api_v1_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateGroupResponse) ProtoMessage() {}

func (x *GetTemplateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateGroupResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{25}
}

type ListTemplateGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateGroupsRequest) Reset() {
	*x = ListTemplateGroupsRequest{}
	mi := &file_api_v1_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateGroupsRequest) ProtoMessage() {}

func (x *ListTemplateGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTemplateGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{26}
}

type ListTemplateGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateGroupsResponse) Reset() {
	*x = ListTemplateGroupsResponse{}
	mi := &file_api_v1_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateGroupsResponse) ProtoMessage() {}

func (x *ListTemplateGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTemplateGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{27}
}

var File_api_v1_service_proto protoreflect.FileDescriptor

const file_api_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/service.proto\x12\x0ens.template.v1\"\xc3\x01\n" +
	"\bTemplate\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12=\n" +
	"\achannel\x18\x05 \x01(\x0e2#.ns.template.v1.TemplateChannelTypeR\achannel\x12\x1c\n" +
	"\tvariables\x18\x06 \x03(\tR\tvariables\"\xaa\x02\n" +
	"\rTemplateGroup\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\ttemplates\x18\x04 \x03(\v2\x18.ns.template.v1.TemplateR\ttemplates\x12W\n" +
	"\x0emeta_variables\x18\x05 \x03(\v20.ns.template.v1.TemplateGroup.MetaVariablesEntryR\rmetaVariables\x1a@\n" +
	"\x12MetaVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12=\n" +
	"\achannel\x18\x04 \x01(\x0e2#.ns.template.v1.TemplateChannelTypeR\achannel\x12\x1c\n" +
	"\tvariables\x18\x05 \x03(\tR\tvariables\"N\n" +
	"\x16CreateTemplateResponse\x124\n" +
	"\btemplate\x18\x01 \x01(\v2\x18.ns.template.v1.TemplateR\btemplate\"b\n" +
	"\x16CreateTemplatesRequest\x12H\n" +
	"\ttemplates\x18\x01 \x03(\v2*.ns.template.v1.CreateTemplateGroupRequestR\ttemplates\"Q\n" +
	"\x17CreateTemplatesResponse\x126\n" +
	"\ttemplates\x18\x01 \x03(\v2\x18.ns.template.v1.TemplateR\ttemplates\"M\n" +
	"\x15UpdateTemplateRequest\x124\n" +
	"\btemplate\x18\x01 \x01(\v2\x18.ns.template.v1.TemplateR\btemplate\"N\n" +
	"\x16UpdateTemplateResponse\x124\n" +
	"\btemplate\x18\x01 \x01(\v2\x18.ns.template.v1.TemplateR\btemplate\")\n" +
	"\x15DeleteTemplateRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\x18\n" +
	"\x16DeleteTemplateResponse\",\n" +
	"\x16DeleteTemplatesRequest\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\tR\x04uids\"\x19\n" +
	"\x17DeleteTemplatesResponse\"&\n" +
	"\x12GetTemplateRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"K\n" +
	"\x13GetTemplateResponse\x124\n" +
	"\btemplate\x18\x01 \x01(\v2\x18.ns.template.v1.TemplateR\btemplate\"*\n" +
	"\x14ListTemplatesRequest\x12\x12\n" +
	"\x04uids\x18\x01 \x01(\tR\x04uids\"O\n" +
	"\x15ListTemplatesResponse\x126\n" +
	"\ttemplates\x18\x01 \x03(\v2\x18.ns.template.v1.TemplateR\ttemplates\"\xa6\x02\n" +
	"\x1aCreateTemplateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\ttemplates\x18\x03 \x03(\v2\x18.ns.template.v1.TemplateR\ttemplates\x12[\n" +
	"\vmeta_params\x18\x04 \x03(\v2:.ns.template.v1.CreateTemplateGroupRequest.MetaParamsEntryR\n" +
	"metaParams\x1a=\n" +
	"\x0fMetaParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\x1bCreateTemplateGroupResponse\"\x1c\n" +
	"\x1aUpdateTemplateGroupRequest\"\x1d\n" +
	"\x1bUpdateTemplateGroupResponse\"\x1c\n" +
	"\x1aDeleteTemplateGroupRequest\"\x1d\n" +
	"\x1bDeleteTemplateGroupResponse\"\x1d\n" +
	"\x1bDeleteTemplateGroupsRequest\"\x1e\n" +
	"\x1cDeleteTemplateGroupsResponse\"\x19\n" +
	"\x17GetTemplateGroupRequest\"\x1a\n" +
	"\x18GetTemplateGroupResponse\"\x1b\n" +
	"\x19ListTemplateGroupsRequest\"\x1c\n" +
	"\x1aListTemplateGroupsResponse*\x91\x01\n" +
	"\x13TemplateChannelType\x12\x1b\n" +
	"\x17CHANNELTYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANNELTYPE_IN_APP\x10\x01\x12\x19\n" +
	"\x15CHANNELTYPE_MESSENGER\x10\x02\x12\x15\n" +
	"\x11CHANNELTYPE_EMAIL\x10\x03\x12\x13\n" +
	"\x0fCHANNELTYPE_SMS\x10\x042\xee\t\n" +
	"\x0fTemplateService\x12a\n" +
	"\x0eCreateTemplate\x12%.ns.template.v1.CreateTemplateRequest\x1a&.ns.template.v1.CreateTemplateResponse\"\x00\x12d\n" +
	"\x0fCreateTemplates\x12&.ns.template.v1.CreateTemplatesRequest\x1a'.ns.template.v1.CreateTemplatesResponse\"\x00\x12a\n" +
	"\x0eUpdateTemplate\x12%.ns.template.v1.UpdateTemplateRequest\x1a&.ns.template.v1.UpdateTemplateResponse\"\x00\x12a\n" +
	"\x0eDeleteTemplate\x12%.ns.template.v1.DeleteTemplateRequest\x1a&.ns.template.v1.DeleteTemplateResponse\"\x00\x12d\n" +
	"\x0fDeleteTemplates\x12&.ns.template.v1.DeleteTemplatesRequest\x1a'.ns.template.v1.DeleteTemplatesResponse\"\x00\x12X\n" +
	"\vGetTemplate\x12\".ns.template.v1.GetTemplateRequest\x1a#.ns.template.v1.GetTemplateResponse\"\x00\x12^\n" +
	"\rListTemplates\x12$.ns.template.v1.ListTemplatesRequest\x1a%.ns.template.v1.ListTemplatesResponse\"\x00\x12p\n" +
	"\x13CreateTemplateGroup\x12*.ns.template.v1.CreateTemplateGroupRequest\x1a+.ns.template.v1.CreateTemplateGroupResponse\"\x00\x12p\n" +
	"\x13UpdateTemplateGroup\x12*.ns.template.v1.UpdateTemplateGroupRequest\x1a+.ns.template.v1.UpdateTemplateGroupResponse\"\x00\x12p\n" +
	"\x13DeleteTemplateGroup\x12*.ns.template.v1.DeleteTemplateGroupRequest\x1a+.ns.template.v1.DeleteTemplateGroupResponse\"\x00\x12g\n" +
	"\x10GetTemplateGroup\x12'.ns.template.v1.GetTemplateGroupRequest\x1a(.ns.template.v1.GetTemplateGroupResponse\"\x00\x12m\n" +
	"\x12ListTemplateGroups\x12).ns.template.v1.ListTemplateGroupsRequest\x1a*.ns.template.v1.ListTemplateGroupsResponse\"\x00B*Z(github.com/neyrzx-ns/template-service/v1b\x06proto3"

var (
	file_api_v1_service_proto_rawDescOnce sync.Once
	file_api_v1_service_proto_rawDescData []byte
)

func file_api_v1_service_proto_rawDescGZIP() []byte {
	file_api_v1_service_proto_rawDescOnce.Do(func() {
		file_api_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_service_proto_rawDesc), len(file_api_v1_service_proto_rawDesc)))
	})
	return file_api_v1_service_proto_rawDescData
}

var file_api_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_v1_service_proto_goTypes = []any{
	(TemplateChannelType)(0),             // 0: ns.template.v1.TemplateChannelType
	(*Template)(nil),                     // 1: ns.template.v1.Template
	(*TemplateGroup)(nil),                // 2: ns.template.v1.TemplateGroup
	(*CreateTemplateRequest)(nil),        // 3: ns.template.v1.CreateTemplateRequest
	(*CreateTemplateResponse)(nil),       // 4: ns.template.v1.CreateTemplateResponse
	(*CreateTemplatesRequest)(nil),       // 5: ns.template.v1.CreateTemplatesRequest
	(*CreateTemplatesResponse)(nil),      // 6: ns.template.v1.CreateTemplatesResponse
	(*UpdateTemplateRequest)(nil),        // 7: ns.template.v1.UpdateTemplateRequest
	(*UpdateTemplateResponse)(nil),       // 8: ns.template.v1.UpdateTemplateResponse
	(*DeleteTemplateRequest)(nil),        // 9: ns.template.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),       // 10: ns.template.v1.DeleteTemplateResponse
	(*DeleteTemplatesRequest)(nil),       // 11: ns.template.v1.DeleteTemplatesRequest
	(*DeleteTemplatesResponse)(nil),      // 12: ns.template.v1.DeleteTemplatesResponse
	(*GetTemplateRequest)(nil),           // 13: ns.template.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),          // 14: ns.template.v1.GetTemplateResponse
	(*ListTemplatesRequest)(nil),         // 15: ns.template.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),        // 16: ns.template.v1.ListTemplatesResponse
	(*CreateTemplateGroupRequest)(nil),   // 17: ns.template.v1.CreateTemplateGroupRequest
	(*CreateTemplateGroupResponse)(nil),  // 18: ns.template.v1.CreateTemplateGroupResponse
	(*UpdateTemplateGroupRequest)(nil),   // 19: ns.template.v1.UpdateTemplateGroupRequest
	(*UpdateTemplateGroupResponse)(nil),  // 20: ns.template.v1.UpdateTemplateGroupResponse
	(*DeleteTemplateGroupRequest)(nil),   // 21: ns.template.v1.DeleteTemplateGroupRequest
	(*DeleteTemplateGroupResponse)(nil),  // 22: ns.template.v1.DeleteTemplateGroupResponse
	(*DeleteTemplateGroupsRequest)(nil),  // 23: ns.template.v1.DeleteTemplateGroupsRequest
	(*DeleteTemplateGroupsResponse)(nil), // 24: ns.template.v1.DeleteTemplateGroupsResponse
	(*GetTemplateGroupRequest)(nil),      // 25: ns.template.v1.GetTemplateGroupRequest
	(*GetTemplateGroupResponse)(nil),     // 26: ns.template.v1.GetTemplateGroupResponse
	(*ListTemplateGroupsRequest)(nil),    // 27: ns.template.v1.ListTemplateGroupsRequest
	(*ListTemplateGroupsResponse)(nil),   // 28: ns.template.v1.ListTemplateGroupsResponse
	nil,                                  // 29: ns.template.v1.TemplateGroup.MetaVariablesEntry
	nil,                                  // 30: ns.template.v1.CreateTemplateGroupRequest.MetaParamsEntry
}
var file_api_v1_service_proto_depIdxs = []int32{
	0,  // 0: ns.template.v1.Template.channel:type_name -> ns.template.v1.TemplateChannelType
	1,  // 1: ns.template.v1.TemplateGroup.templates:type_name -> ns.template.v1.Template
	29, // 2: ns.template.v1.TemplateGroup.meta_variables:type_name -> ns.template.v1.TemplateGroup.MetaVariablesEntry
	0,  // 3: ns.template.v1.CreateTemplateRequest.channel:type_name -> ns.template.v1.TemplateChannelType
	1,  // 4: ns.template.v1.CreateTemplateResponse.template:type_name -> ns.template.v1.Template
	17, // 5: ns.template.v1.CreateTemplatesRequest.templates:type_name -> ns.template.v1.CreateTemplateGroupRequest
	1,  // 6: ns.template.v1.CreateTemplatesResponse.templates:type_name -> ns.template.v1.Template
	1,  // 7: ns.template.v1.UpdateTemplateRequest.template:type_name -> ns.template.v1.Template
	1,  // 8: ns.template.v1.UpdateTemplateResponse.template:type_name -> ns.template.v1.Template
	1,  // 9: ns.template.v1.GetTemplateResponse.template:type_name -> ns.template.v1.Template
	1,  // 10: ns.template.v1.ListTemplatesResponse.templates:type_name -> ns.template.v1.Template
	1,  // 11: ns.template.v1.CreateTemplateGroupRequest.templates:type_name -> ns.template.v1.Template
	30, // 12: ns.template.v1.CreateTemplateGroupRequest.meta_params:type_name -> ns.template.v1.CreateTemplateGroupRequest.MetaParamsEntry
	3,  // 13: ns.template.v1.TemplateService.CreateTemplate:input_type -> ns.template.v1.CreateTemplateRequest
	5,  // 14: ns.template.v1.TemplateService.CreateTemplates:input_type -> ns.template.v1.CreateTemplatesRequest
	7,  // 15: ns.template.v1.TemplateService.UpdateTemplate:input_type -> ns.template.v1.UpdateTemplateRequest
	9,  // 16: ns.template.v1.TemplateService.DeleteTemplate:input_type -> ns.template.v1.DeleteTemplateRequest
	11, // 17: ns.template.v1.TemplateService.DeleteTemplates:input_type -> ns.template.v1.DeleteTemplatesRequest
	13, // 18: ns.template.v1.TemplateService.GetTemplate:input_type -> ns.template.v1.GetTemplateRequest
	15, // 19: ns.template.v1.TemplateService.ListTemplates:input_type -> ns.template.v1.ListTemplatesRequest
	17, // 20: ns.template.v1.TemplateService.CreateTemplateGroup:input_type -> ns.template.v1.CreateTemplateGroupRequest
	19, // 21: ns.template.v1.TemplateService.UpdateTemplateGroup:input_type -> ns.template.v1.UpdateTemplateGroupRequest
	21, // 22: ns.template.v1.TemplateService.DeleteTemplateGroup:input_type -> ns.template.v1.DeleteTemplateGroupRequest
	25, // 23: ns.template.v1.TemplateService.GetTemplateGroup:input_type -> ns.template.v1.GetTemplateGroupRequest
	27, // 24: ns.template.v1.TemplateService.ListTemplateGroups:input_type -> ns.template.v1.ListTemplateGroupsRequest
	4,  // 25: ns.template.v1.TemplateService.CreateTemplate:output_type -> ns.template.v1.CreateTemplateResponse
	6,  // 26: ns.template.v1.TemplateService.CreateTemplates:output_type -> ns.template.v1.CreateTemplatesResponse
	8,  // 27: ns.template.v1.TemplateService.UpdateTemplate:output_type -> ns.template.v1.UpdateTemplateResponse
	10, // 28: ns.template.v1.TemplateService.DeleteTemplate:output_type -> ns.template.v1.DeleteTemplateResponse
	12, // 29: ns.template.v1.TemplateService.DeleteTemplates:output_type -> ns.template.v1.DeleteTemplatesResponse
	14, // 30: ns.template.v1.TemplateService.GetTemplate:output_type -> ns.template.v1.GetTemplateResponse
	16, // 31: ns.template.v1.TemplateService.ListTemplates:output_type -> ns.template.v1.ListTemplatesResponse
	18, // 32: ns.template.v1.TemplateService.CreateTemplateGroup:output_type -> ns.template.v1.CreateTemplateGroupResponse
	20, // 33: ns.template.v1.TemplateService.UpdateTemplateGroup:output_type -> ns.template.v1.UpdateTemplateGroupResponse
	22, // 34: ns.template.v1.TemplateService.DeleteTemplateGroup:output_type -> ns.template.v1.DeleteTemplateGroupResponse
	26, // 35: ns.template.v1.TemplateService.GetTemplateGroup:output_type -> ns.template.v1.GetTemplateGroupResponse
	28, // 36: ns.template.v1.TemplateService.ListTemplateGroups:output_type -> ns.template.v1.ListTemplateGroupsResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_v1_service_proto_init() }
func file_api_v1_service_proto_init() {
	if File_api_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_service_proto_rawDesc), len(file_api_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_service_proto_goTypes,
		DependencyIndexes: file_api_v1_service_proto_depIdxs,
		EnumInfos:         file_api_v1_service_proto_enumTypes,
		MessageInfos:      file_api_v1_service_proto_msgTypes,
	}.Build()
	File_api_v1_service_proto = out.File
	file_api_v1_service_proto_goTypes = nil
	file_api_v1_service_proto_depIdxs = nil
}
